import {
  ArrowRight,
  Check,
  CirclePlay,
  Film,
  Mic2,
  RefreshCw,
  ScanFace,
  ShieldCheck,
  Sparkles,
} from 'lucide-react';
import Image from 'next/image';
import type {Locale} from '../content';
import {path} from '../content';
import {HeaderV2} from './HeaderV2';
import {FooterV2} from './FooterV2';
import {Button} from './ui/button';

function StudioPreview({locale}:{locale:Locale}) {
  const id=locale==='id';
  return <div className="relative rounded-[24px] border border-black/10 bg-[#1d1d1b] p-2 shadow-[0_32px_90px_rgba(50,42,32,.22)]">
    <div className="flex h-10 items-center justify-between px-3 text-[9px] font-bold tracking-[.14em] text-white/35"><span className="flex gap-1.5"><i className="size-2 rounded-full bg-[#ff7250]"/><i className="size-2 rounded-full bg-[#ead07f]"/><i className="size-2 rounded-full bg-white/20"/></span><span>AUTOVID STUDIO</span><span className="text-[#9bd2b5]">● READY</span></div>
    <div className="grid min-h-[390px] grid-cols-[78px_1fr] overflow-hidden rounded-[17px] bg-[#f7f4ee]">
      <aside className="border-r border-black/10 bg-[#ede8de] p-3"><Image src="/autovid-logo-v2.png" alt="" width={36} height={36} className="mb-8 size-9 object-contain"/>{[Film,Sparkles,Mic2,CirclePlay].map((Icon,i)=><span key={i} className={`mb-2 grid size-9 place-items-center rounded-xl ${i===1?'bg-[#ff6338] text-white':'text-black/35'}`}><Icon className="size-4"/></span>)}</aside>
      <section className="min-w-0 p-5 sm:p-7"><div className="flex items-start justify-between"><div><small className="text-[8px] font-extrabold tracking-[.16em] text-black/35">{id?'PROJECT AKTIF':'ACTIVE PROJECT'}</small><h3 className="mt-1 text-xl font-extrabold tracking-[-.045em] text-[#1d1c1a]">The Fallen Heir</h3></div><span className="rounded-full bg-[#e3f0e8] px-2.5 py-1 text-[8px] font-bold text-[#34704d]">● {id?'Membuat visual':'Generating'}</span></div>
        <div className="mt-6 grid grid-cols-3 gap-2">{[['SCENES','37 / 60'],['VOICE','60 ready'],['ACCOUNT','google-2']].map(([a,b])=><div key={a} className="rounded-xl border border-black/10 bg-white p-3"><small className="text-[7px] font-bold tracking-[.12em] text-black/35">{a}</small><b className="mt-1 block truncate text-[11px] text-black/75">{b}</b></div>)}</div>
        <div className="mt-3 rounded-2xl border border-black/10 bg-white p-4"><div className="flex justify-between text-[9px] font-semibold text-black/45"><span>{id?'Progress scene':'Scene progress'}</span><b className="text-[#e7562e]">62%</b></div><div className="my-3 h-1 rounded-full bg-black/5"><i className="block h-full w-[62%] rounded-full bg-[#ff6338]"/></div><div className="grid grid-cols-5 gap-1.5">{Array.from({length:10},(_,i)=><span key={i} className={`aspect-[1.5] rounded-md border ${i<6?'border-[#f0b39e] bg-[#fff0e9]':i===6?'border-[#ff6338] bg-[#fff] ring-2 ring-[#ff6338]/15':'border-black/5 bg-[#f4f1eb]'}`}/>)}</div></div>
        <div className="mt-3 flex items-center gap-2 rounded-xl bg-[#e8f1ec] p-3 text-[9px] text-[#42614e]"><Check className="size-3.5"/><b>{id?'Progress aman.':'Progress protected.'}</b><span className="hidden sm:inline">{id?'Scene selesai tidak diulang.':'Finished scenes are not repeated.'}</span></div>
      </section>
    </div>
  </div>;
}

export function HomeV2({locale}:{locale:Locale}) {
  const id=locale==='id';
  return <div className="min-h-screen bg-[#f5f2ec] text-[#1d1c1a]"><HeaderV2 locale={locale}/><main>
    <section className="relative overflow-hidden border-b border-black/10"><div className="pointer-events-none absolute -right-32 top-20 size-[420px] rounded-full bg-[#bed7ff]/35 blur-3xl"/><div className="mx-auto grid min-h-[720px] w-[min(1180px,calc(100%-32px))] items-center gap-16 py-20 lg:grid-cols-[.92fr_1.08fr] lg:py-24">
      <div className="relative z-10"><span className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white/60 px-3 py-1.5 text-[10px] font-extrabold tracking-[.13em] text-black/55"><RefreshCw className="size-3 text-[#ff6338]"/>{id?'PIPELINE YANG BISA DILANJUTKAN':'A PIPELINE YOU CAN RESUME'}</span><h1 className="mt-7 max-w-[650px] text-[clamp(48px,6vw,82px)] font-extrabold leading-[.98] tracking-[-.072em]">{id?'Satu meja kerja. Semua tahap produksi ': 'One workspace for every stage of '}<span className="font-serif font-medium italic tracking-[-.04em] text-[#e8562f]">{id?'video.':'production.'}</span></h1><p className="mt-7 max-w-[590px] text-[16px] leading-7 text-[#686159]">{id?'Tulis cerita, cocokkan voice-over, buat visual konsisten, lalu render. AutoVid menjaga scene yang sudah selesai tetap aman saat akun Google Flow berhenti.':'Write the story, fit the voice-over, create consistent visuals, then render. AutoVid keeps finished scenes safe when a Google Flow account stops.'}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" variant="accent"><a href={path(locale,'/download')}>{id?'Download Windows':'Download for Windows'}<ArrowRight className="size-4"/></a></Button><Button asChild size="lg" variant="outline"><a href={path(locale,'/features')}>{id?'Lihat cara kerjanya':'See how it works'}</a></Button></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-2 text-[11px] font-semibold text-black/50"><span>✓ {id?'Sekali beli Rp150.000':'IDR 150,000 one-time'}</span><span>✓ {id?'Progress tersimpan':'Checkpointed progress'}</span><span>✓ {id?'File tetap lokal':'Local project files'}</span></div></div>
      <div className="relative"><div className="absolute -left-10 -top-9 -rotate-6 rounded-full bg-[#dcebd9] px-4 py-2 text-xs font-bold text-[#335c3d] shadow-sm">{id?'Bukan sekadar generator':'More than a generator'}</div><StudioPreview locale={locale}/><div className="absolute -bottom-6 right-6 rotate-3 rounded-2xl border border-black/10 bg-[#fffaf2] p-4 shadow-lg"><small className="block text-[8px] font-bold tracking-[.14em] text-black/35">{id?'SCENE TERAKHIR':'LAST SCENE'}</small><b className="mt-1 block text-sm">037 · Saved ✓</b></div></div>
    </div></section>
    <section className="mx-auto grid w-[min(1180px,calc(100%-32px))] gap-6 border-b border-black/10 py-10 text-sm text-black/55 md:grid-cols-[1.1fr_1fr_1fr]"><b className="text-black">{id?'Dibuat untuk produksi scene panjang.':'Built for long scene-based productions.'}</b><span>{id?'Manhwa recap · faceless story · AI image story':'Manhwa recap · faceless story · AI image story'}</span><span className="md:text-right">Windows 10/11 · x64</span></section>
    <section className="shell-v2 py-24 md:py-32"><div className="grid gap-10 md:grid-cols-[.7fr_1.3fr]"><span className="eyebrow-v2">{id?'ALUR YANG TERHUBUNG':'A CONNECTED WORKFLOW'}</span><div><h2 className="max-w-3xl text-[clamp(40px,5.2vw,68px)] font-extrabold leading-[1.02] tracking-[-.065em]">{id?'Dari halaman kosong sampai video siap unggah.':'From a blank page to an upload-ready video.'}</h2><p className="mt-6 max-w-2xl text-base leading-7 text-[#6b645c]">{id?'Setiap tahap menyerahkan hasil yang terverifikasi ke tahap berikutnya—tanpa folder acak dan tanpa menebak proses berhenti di mana.':'Each stage hands verified output to the next—without scattered folders or guessing where the process stopped.'}</p></div></div><div className="mt-16 grid md:grid-cols-4">{(id?[['01','Story','Bangun naskah dan scene.'],['02','Voice','Sesuaikan narasi per durasi.'],['03','Visual','Jaga style dan karakter.'],['04','Render','Ekspor hasil final.']]:[['01','Story','Build the script and scenes.'],['02','Voice','Fit narration to duration.'],['03','Visuals','Keep style and characters.'],['04','Render','Export the final cut.']]).map(([n,t,d])=><article key={n} className="border-t border-black/15 py-6 md:border-r md:px-6 md:first:pl-0 md:last:border-r-0"><span className="font-serif text-3xl italic text-[#e8562f]">{n}</span><h3 className="mt-9 text-xl font-extrabold tracking-[-.04em]">{t}</h3><p className="mt-2 text-sm leading-6 text-black/45">{d}</p></article>)}</div></section>
    <section className="border-y border-black/10 bg-[#e8e2d8]"><div className="shell-v2 grid gap-14 py-24 lg:grid-cols-[.9fr_1.1fr]"><div><span className="eyebrow-v2">{id?'DIBUAT UNTUK KONDISI NYATA':'BUILT FOR REAL CONDITIONS'}</span><h2 className="mt-6 text-[clamp(40px,5vw,64px)] font-extrabold leading-[1.02] tracking-[-.065em]">{id?'Pipeline boleh berhenti. Project tidak boleh hilang.':'The pipeline may stop. Your project should not disappear.'}</h2></div><div className="divide-y divide-black/10 border-t border-black/10">{[[RefreshCw,id?'Ganti akun, lanjutkan scene':'Switch accounts, continue the scene',id?'Ketika satu profil Flow mencapai limit, scene selesai tetap selesai.':'When one Flow profile reaches its limit, completed scenes stay complete.'],[ScanFace,id?'Reference tetap reference':'References stay references',id?'Character sheet tidak bercampur dengan hasil artwork scene.':'Character sheets never mix with finished scene artwork.'],[ShieldCheck,id?'Checkpoint sebelum render':'Checkpoint before render',id?'Asset diverifikasi sebelum masuk ke tahap berikutnya.':'Assets are verified before moving downstream.']].map(([Icon,t,d])=>{const C=Icon as typeof RefreshCw;return <article key={String(t)} className="grid grid-cols-[44px_1fr] gap-4 py-7"><span className="grid size-10 place-items-center rounded-xl bg-[#f5f2ec]"><C className="size-4.5 text-[#e8562f]"/></span><div><h3 className="text-lg font-extrabold tracking-[-.035em]">{String(t)}</h3><p className="mt-2 text-sm leading-6 text-black/50">{String(d)}</p></div></article>})}</div></div></section>
    <section className="shell-v2 grid gap-8 py-24 md:grid-cols-[1fr_.8fr] md:items-end"><div><span className="eyebrow-v2">{id?'HARGA SEDERHANA':'SIMPLE PRICING'}</span><h2 className="mt-5 text-[clamp(44px,5vw,66px)] font-extrabold tracking-[-.07em]">Rp150.000 <span className="font-serif text-3xl font-medium italic text-black/35">{id?'sekali beli':'one-time'}</span></h2><p className="mt-5 max-w-xl text-sm leading-7 text-black/50">{id?'Tidak ada biaya langganan bulanan AutoVid. Layanan AI pihak ketiga dapat memiliki biaya atau kuota sendiri.':'No monthly AutoVid subscription fee. Third-party AI services may have their own charges or quotas.'}</p></div><div className="flex flex-col gap-3 md:items-end"><Button asChild size="lg" variant="accent"><a href={path(locale,'/download')}>{id?'Download dan beli lisensi':'Download and buy a license'}<ArrowRight className="size-4"/></a></Button><span className="text-[10px] text-black/40">{id?'Checkout Lynk.id segera setelah tautan produk tersedia.':'Lynk.id checkout once the product link is ready.'}</span></div></section>
  </main><FooterV2 locale={locale}/></div>;
}
